# Show SQL in dev
spring.jpa.show-sql=true

# Flyway
spring.flyway.clean-disabled=false
spring.flyway.locations=classpath:db/migration,classpath:db/seed

# Google OAuth
google.redirect-uri=http://localhost:3000/auth/google/callback

# Logging
logging.level.com.tasklean=DEBUG
logging.level.org.hibernate.SQL=DEBUG